#!/bin/bash

echo "### 1. agent_run表结构 + 最近任务步数 ###"
MP=$(docker exec coze-mysql printenv MYSQL_ROOT_PASSWORD)
echo "--- agent_run相关表 ---"
docker exec coze-mysql mysql -uroot -p"$MP" opencoze -N -e "
SELECT table_name FROM information_schema.tables WHERE table_schema='opencoze' AND table_name LIKE '%run%';" 2>/dev/null

echo ""
echo "--- 查含step/iteration字段的列 ---"
docker exec coze-mysql mysql -uroot -p"$MP" opencoze -N -e "
SELECT table_name, column_name FROM information_schema.columns 
WHERE table_schema='opencoze' AND (column_name LIKE '%step%' OR column_name LIKE '%iteration%') 
LIMIT 20;" 2>/dev/null

echo ""
echo "### 2. 并发视频实测（脚本base64内嵌）###"
echo "aW1wb3J0IHVybGxpYi5yZXF1ZXN0LCBqc29uLCBjb25jdXJyZW50LmZ1dHVyZXMsIHRpbWUKCkJBU0UgPSAnaHR0cDovL2xvY2FsaG9zdDo5MDkyJwpVU0VSID0gJ2NvbmNfYXVkaXRfdXNlcicKCmRlZiBjYWxsKGFjdGlvbiwgcHJvbXB0X2lkLCBwcm9tcHQpOgogICAgcmVxID0gdXJsbGliLnJlcXVlc3QuUmVxdWVzdCgKICAgICAgICBmJ3tCQVNFfS92aWRlby9nZW5lcmF0ZScsCiAgICAgICAgZGF0YT1qc29uLmR1bXBzKHsnYWN0aW9uJzphY3Rpb24sJ2R1cmF0aW9uJzo1LCdwcm9tcHQnOnByb21wdH0pLmVuY29kZSgpLAogICAgICAgIGhlYWRlcnM9eydDb250ZW50LVR5cGUnOidhcHBsaWNhdGlvbi9qc29uJywnWC1BaXBsdWdpbi1Db25uZWN0b3ItSWRlbnRpZmllcic6VVNFUn0KICAgICkKICAgIHRyeToKICAgICAgICByZXNwID0gdXJsbGliLnJlcXVlc3QudXJsb3BlbihyZXEsIHRpbWVvdXQ9NjApCiAgICAgICAgcmV0dXJuIHByb21wdF9pZCwganNvbi5sb2FkcyhyZXNwLnJlYWQoKS5kZWNvZGUoKSksIE5vbmUKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICByZXR1cm4gcHJvbXB0X2lkLCBOb25lLCBzdHIoZSkKCiMgNCBjb25jdXJyZW50IHF1b3Rlcwp0MD10aW1lLnRpbWUoKQp3aXRoIGNvbmN1cnJlbnQuZnV0dXJlcy5UaHJlYWRQb29sRXhlY3V0b3IobWF4X3dvcmtlcnM9NCkgYXMgZXg6CiAgICBxcmVzdWx0cyA9IGxpc3QoZXgubWFwKGxhbWJkYSBpOiBjYWxsKCdxdW90ZScsIGksIGYncXVvdGUgc2NlbmUge2l9IHt0aW1lLnRpbWUoKX0nKSwgcmFuZ2UoNCkpKQpwcmludChmIjQgY29uY3VycmVudCBxdW90ZXMgaW4ge3RpbWUudGltZSgpLXQwOi4xZn1zOiIpCmZvciBwaWQsIGRhdGEsIGVyciBpbiBxcmVzdWx0czoKICAgIGlmIGVycjogcHJpbnQoZiIgIHF1b3RlIHtwaWR9OiBFUlJPUiB7ZXJyfSIpOyBjb250aW51ZQogICAgb2sgPSBpc2luc3RhbmNlKGRhdGEuZ2V0KCdkYXRhJyksIHN0cikKICAgIHByaW50KGYiICBxdW90ZSB7cGlkfTogZGF0YV9pc19zdHJpbmc9e29rfSIpCgp0aW1lLnNsZWVwKDEpCiMgNCBjb25jdXJyZW50IGdlbmVyYXRlcwpwcm9tcHRzID0gWyJnaXJsIGRhbmNpbmcgaGFuZnUgZ2FyZGVuIiwid29tYW4gd2Fsa2luZyBhbmNpZW50IHN0cmVldCIsCiAgICAgICAgICAgImdpcmwgcGxheWluZyBpbnN0cnVtZW50IG1vb25saWdodCIsInByaW5jZXNzIHNwaW5uaW5nIHBhbGFjZSJdCnQwPXRpbWUudGltZSgpCndpdGggY29uY3VycmVudC5mdXR1cmVzLlRocmVhZFBvb2xFeGVjdXRvcihtYXhfd29ya2Vycz00KSBhcyBleDoKICAgIGdyZXN1bHRzID0gbGlzdChleC5tYXAobGFtYmRhIGk6IGNhbGwoJ2dlbmVyYXRlJywgaSwgZid7cHJvbXB0c1tpXX0gc3tpfSB7dGltZS50aW1lKCl9JyksIHJhbmdlKDQpKSkKcHJpbnQoZiJcbjQgY29uY3VycmVudCBHRU5FUkFURSBpbiB7dGltZS50aW1lKCktdDA6LjFmfXM6IikKdGlkcz1bXQpmb3IgcGlkLCBkYXRhLCBlcnIgaW4gZ3Jlc3VsdHM6CiAgICBpZiBlcnI6IHByaW50KGYiICBnZW4ge3BpZH06IEVSUk9SIHtlcnJ9Iik7IGNvbnRpbnVlCiAgICByYXc9ZGF0YS5nZXQoJ2RhdGEnKQogICAgaWYgbm90IGlzaW5zdGFuY2UocmF3LHN0cik6CiAgICAgICAgcHJpbnQoZiIgIGdlbiB7cGlkfTogZGF0YSBOT1Qgc3RyaW5nISB7dHlwZShyYXcpLl9fbmFtZV9ffSIpOyBjb250aW51ZQogICAgaW5uZXI9anNvbi5sb2FkcyhyYXcpCiAgICB0aWQ9aW5uZXIuZ2V0KCd0YXNrX2lkJykKICAgIGlmIHRpZDogdGlkcy5hcHBlbmQodGlkKQogICAgcHJpbnQoZiIgIGdlbiB7cGlkfTogdGFza19pZD17dGlkfSwgc3RhdHVzPXtpbm5lci5nZXQoJ3N0YXR1cycpfSwgY29zdD17aW5uZXIuZ2V0KCdjb3N0Jyl9LCBiYWxhbmNlPXtpbm5lci5nZXQoJ2JhbGFuY2UnKX0iKQoKcHJpbnQoZiJcbj09PSBSRVNVTFQ6IHtsZW4odGlkcyl9LzQgdGFza19pZHMsIGFsbF91bmlxdWU9e2xlbihzZXQodGlkcykpPT1sZW4odGlkcykgYW5kIGxlbih0aWRzKT09NH0gPT09IikKd2l0aCBvcGVuKCcvaG9zdC10bXAvY29uY190aWRzLmpzb24nLCd3JykgYXMgZjoganNvbi5kdW1wKHRpZHMsZikK" | base64 -d > /tmp/conc_run.py
# /tmp 在容器里挂载为 /host-tmp
docker exec tool-proxy python3 /host-tmp/conc_run.py 2>&1

echo ""
echo "### 3. submit日志 ###"
docker logs tool-proxy --since 3m 2>&1 | grep "\[VID\] submit" | tail -6

echo "[DONE]"
